class Product {
  final int id;
  final String name;
  final double price;
  final String category;

  Product({
    required this.id,
    required this.name,
    required this.price,
    required this.category,
  });
}

List<Product> productCollection = [
  Product(id: 1, name: 'CRM App', price: 1000, category: 'B Software'),
  Product(id: 2, name: 'POS System', price: 400, category: 'A Retail'),
  Product(id: 4, name: 'Tour Booking', price: 800, category: 'C Travel'),
  Product(id: 3, name: 'HRM Suite', price: 500, category: 'E SaaS'),
  Product(id: 5, name: 'E-commerce App', price: 100, category: 'D Store'),
  Product(id: 6, name: 'School ERP', price: 150, category: 'Education'),
  Product(id: 7, name: 'Inventory Manager', price: 600, category: 'Warehouse'),
  Product(id: 8, name: 'Task Tracker', price: 500, category: 'Productivity'),
  Product(id: 9, name: 'Portfolio Site', price: 300, category: 'Web'),
  Product(id: 10, name: 'CRM App', price: 1000, category: 'B Software'),
  Product(id: 11, name: 'CRM App', price: 1000, category: 'B Software'),
  Product(id: 12, name: 'POS System', price: 400, category: 'A Retail'),
  Product(id: 14, name: 'Tour Booking', price: 800, category: 'C Travel'),
  Product(id: 13, name: 'HRM Suite', price: 500, category: 'E SaaS'),
  Product(id: 15, name: 'E-commerce App', price: 100, category: 'D Store'),
  Product(id: 16, name: 'School ERP', price: 150, category: 'Education'),
  Product(id: 17, name: 'Inventory Manager', price: 600, category: 'Warehouse'),
  Product(id: 18, name: 'Task Tracker', price: 500, category: 'Productivity'),
  Product(id: 19, name: 'Portfolio Site', price: 300, category: 'Web'),
  Product(id: 20, name: 'POS System', price: 400, category: 'A Retail'),
  Product(id: 21, name: 'CRM App', price: 1000, category: 'B Software'),
  Product(id: 22, name: 'POS System', price: 400, category: 'A Retail'),
  Product(id: 24, name: 'Tour Booking', price: 800, category: 'C Travel'),
  Product(id: 23, name: 'HRM Suite', price: 500, category: 'E SaaS'),
  Product(id: 25, name: 'E-commerce App', price: 100, category: 'D Store'),
  Product(id: 26, name: 'School ERP', price: 150, category: 'Education'),
  Product(id: 27, name: 'Inventory Manager', price: 600, category: 'Warehouse'),
  Product(id: 28, name: 'Task Tracker', price: 500, category: 'Productivity'),
  Product(id: 29, name: 'Portfolio Site', price: 300, category: 'Web'),
  Product(id: 30, name: 'HRM Suite', price: 500, category: 'E SaaS'),
  Product(id: 31, name: 'CRM App', price: 1000, category: 'B Software'),
  Product(id: 32, name: 'POS System', price: 400, category: 'A Retail'),
  Product(id: 34, name: 'Tour Booking', price: 800, category: 'C Travel'),
  Product(id: 33, name: 'HRM Suite', price: 500, category: 'E SaaS'),
  Product(id: 35, name: 'E-commerce App', price: 100, category: 'D Store'),
  Product(id: 36, name: 'School ERP', price: 150, category: 'Education'),
  Product(id: 37, name: 'Inventory Manager', price: 600, category: 'Warehouse'),
  Product(id: 38, name: 'Task Tracker', price: 500, category: 'Productivity'),
  Product(id: 39, name: 'Portfolio Site', price: 300, category: 'Web'),
  Product(id: 40, name: 'Tour Booking', price: 800, category: 'C Travel'),
  Product(id: 41, name: 'CRM App', price: 1000, category: 'B Software'),
  Product(id: 42, name: 'POS System', price: 400, category: 'A Retail'),
  Product(id: 44, name: 'Tour Booking', price: 800, category: 'C Travel'),
  Product(id: 43, name: 'HRM Suite', price: 500, category: 'E SaaS'),
  Product(id: 45, name: 'E-commerce App', price: 100, category: 'D Store'),
  Product(id: 46, name: 'School ERP', price: 150, category: 'Education'),
  Product(id: 47, name: 'Inventory Manager', price: 600, category: 'Warehouse'),
  Product(id: 48, name: 'Task Tracker', price: 500, category: 'Productivity'),
  Product(id: 49, name: 'Portfolio Site', price: 300, category: 'Web'),
  Product(id: 50, name: 'E-commerce App', price: 100, category: 'D Store'),
  Product(id: 101, name: 'CRM App', price: 1000, category: 'B Software'),
  Product(id: 102, name: 'POS System', price: 400, category: 'A Retail'),
  Product(id: 104, name: 'Tour Booking', price: 800, category: 'C Travel'),
  Product(id: 103, name: 'HRM Suite', price: 500, category: 'E SaaS'),
  Product(id: 105, name: 'E-commerce App', price: 100, category: 'D Store'),
  Product(id: 106, name: 'School ERP', price: 150, category: 'Education'),
  Product(id: 107, name: 'Inventory Manager', price: 600, category: 'Warehouse'),
  Product(id: 108, name: 'Task Tracker', price: 500, category: 'Productivity'),
  Product(id: 109, name: 'Portfolio Site', price: 300, category: 'Web'),
  Product(id: 110, name: 'CRM App', price: 1000, category: 'B Software'),
  Product(id: 111, name: 'CRM App', price: 1000, category: 'B Software'),
  Product(id: 112, name: 'POS System', price: 400, category: 'A Retail'),
  Product(id: 114, name: 'Tour Booking', price: 800, category: 'C Travel'),
  Product(id: 113, name: 'HRM Suite', price: 500, category: 'E SaaS'),
  Product(id: 115, name: 'E-commerce App', price: 100, category: 'D Store'),
  Product(id: 116, name: 'School ERP', price: 150, category: 'Education'),
  Product(id: 117, name: 'Inventory Manager', price: 600, category: 'Warehouse'),
  Product(id: 118, name: 'Task Tracker', price: 500, category: 'Productivity'),
  Product(id: 119, name: 'Portfolio Site', price: 300, category: 'Web'),
  Product(id: 120, name: 'POS System', price: 400, category: 'A Retail'),
  Product(id: 121, name: 'CRM App', price: 1000, category: 'B Software'),
  Product(id: 122, name: 'POS System', price: 400, category: 'A Retail'),
  Product(id: 124, name: 'Tour Booking', price: 800, category: 'C Travel'),
  Product(id: 123, name: 'HRM Suite', price: 500, category: 'E SaaS'),
  Product(id: 125, name: 'E-commerce App', price: 100, category: 'D Store'),
  Product(id: 126, name: 'School ERP', price: 150, category: 'Education'),
  Product(id: 127, name: 'Inventory Manager', price: 600, category: 'Warehouse'),
  Product(id: 128, name: 'Task Tracker', price: 500, category: 'Productivity'),
  Product(id: 129, name: 'Portfolio Site', price: 300, category: 'Web'),
  Product(id: 130, name: 'HRM Suite', price: 500, category: 'E SaaS'),
  Product(id: 131, name: 'CRM App', price: 1000, category: 'B Software'),
  Product(id: 132, name: 'POS System', price: 400, category: 'A Retail'),
  Product(id: 134, name: 'Tour Booking', price: 800, category: 'C Travel'),
  Product(id: 133, name: 'HRM Suite', price: 500, category: 'E SaaS'),
  Product(id: 135, name: 'E-commerce App', price: 100, category: 'D Store'),
  Product(id: 136, name: 'School ERP', price: 150, category: 'Education'),
  Product(id: 137, name: 'Inventory Manager', price: 600, category: 'Warehouse'),
  Product(id: 138, name: 'Task Tracker', price: 500, category: 'Productivity'),
  Product(id: 139, name: 'Portfolio Site', price: 300, category: 'Web'),
  Product(id: 140, name: 'Tour Booking', price: 800, category: 'C Travel'),
  Product(id: 141, name: 'CRM App', price: 1000, category: 'B Software'),
  Product(id: 142, name: 'POS System', price: 400, category: 'A Retail'),
  Product(id: 144, name: 'Tour Booking', price: 800, category: 'C Travel'),
  Product(id: 143, name: 'HRM Suite', price: 500, category: 'E SaaS'),
  Product(id: 145, name: 'E-commerce App', price: 100, category: 'D Store'),
  Product(id: 146, name: 'School ERP', price: 150, category: 'Education'),
  Product(id: 147, name: 'Inventory Manager', price: 600, category: 'Warehouse'),
  Product(id: 148, name: 'Task Tracker', price: 500, category: 'Productivity'),
  Product(id: 149, name: 'Portfolio Site', price: 300, category: 'Web'),
  Product(id: 150, name: 'E-commerce App', price: 100, category: 'D Store'),
];
